# Generated by Django 6.0.7 on 2026-09-04 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FLAT', 'Flat Amount')], default='PERCENTAGE', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage value (1-100) or flat amount off', max_digits=6)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap on maximum discount for percentage coupons (optional)', max_digits=6, null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum cart total required to apply coupon', max_digits=6)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
